##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: api-franchise
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
adapters:
  r2dbc:
    host: localhost
    port: 5432
    password: root
    database: postgre
    schema: franchise
